spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mhyj?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: root
      login-timeout: 5
      maximum-pool-size: 50


