spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mhyj?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      username: root
      password: root
      maximum-pool-size: 20
      login-timeout: 5