spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mhyj?useSSL=false&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      initial-size: 6
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow: localhost
      web-stat-filter:
        enabled: true